version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: reachinbox-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - reachinbox-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Optional: PostgreSQL with pgvector for RAG features
  postgres:
    image: pgvector/pgvector:pg16
    container_name: reachinbox-postgres
    environment:
      - POSTGRES_DB=reachinbox
      - POSTGRES_USER=reachinbox
      - POSTGRES_PASSWORD=reachinbox123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reachinbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reachinbox -d reachinbox"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: reachinbox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reachinbox-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  elasticsearch_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  reachinbox-network:
    driver: bridge
